/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ProjectId = IDL.Nat;
export const UserId = IDL.Principal;
export const ProjectRole = IDL.Variant({
  'member' : IDL.Null,
  'admin' : IDL.Null,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Timestamp = IDL.Int;
export const TaskId = IDL.Nat;
export const UserProfile = IDL.Record({ 'displayName' : IDL.Text });
export const DashboardStats = IDL.Record({
  'total' : IDL.Nat,
  'pending' : IDL.Nat,
  'completed' : IDL.Nat,
  'overdue' : IDL.Nat,
});
export const ProjectMember = IDL.Record({
  'userId' : UserId,
  'role' : ProjectRole,
});
export const ProjectView = IDL.Record({
  'id' : ProjectId,
  'members' : IDL.Vec(ProjectMember),
  'name' : IDL.Text,
  'createdBy' : UserId,
  'description' : IDL.Text,
});
export const TaskStatus = IDL.Variant({
  'toDo' : IDL.Null,
  'completed' : IDL.Null,
  'inProgress' : IDL.Null,
});
export const TaskView = IDL.Record({
  'id' : TaskId,
  'status' : TaskStatus,
  'title' : IDL.Text,
  'assignedTo' : IDL.Opt(UserId),
  'createdAt' : Timestamp,
  'createdBy' : UserId,
  'dueDate' : Timestamp,
  'description' : IDL.Text,
  'projectId' : ProjectId,
  'isOverdue' : IDL.Bool,
});

export const idlService = IDL.Service({
  '_initializeAccessControl' : IDL.Func([], [], []),
  'addProjectMember' : IDL.Func(
      [ProjectId, UserId, ProjectRole],
      [IDL.Bool],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createProject' : IDL.Func([IDL.Text, IDL.Text], [ProjectId], []),
  'createTask' : IDL.Func(
      [ProjectId, IDL.Text, IDL.Text, Timestamp, IDL.Opt(UserId)],
      [TaskId],
      [],
    ),
  'deleteProject' : IDL.Func([ProjectId], [IDL.Bool], []),
  'deleteTask' : IDL.Func([TaskId], [IDL.Bool], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDashboard' : IDL.Func([], [DashboardStats], ['query']),
  'getProject' : IDL.Func([ProjectId], [IDL.Opt(ProjectView)], ['query']),
  'getTask' : IDL.Func([TaskId], [IDL.Opt(TaskView)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listMyProjects' : IDL.Func([], [IDL.Vec(ProjectView)], ['query']),
  'listProjectTasks' : IDL.Func([ProjectId], [IDL.Vec(TaskView)], ['query']),
  'removeProjectMember' : IDL.Func([ProjectId, UserId], [IDL.Bool], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateProject' : IDL.Func([ProjectId, IDL.Text, IDL.Text], [IDL.Bool], []),
  'updateProjectMemberRole' : IDL.Func(
      [ProjectId, UserId, ProjectRole],
      [IDL.Bool],
      [],
    ),
  'updateTask' : IDL.Func(
      [TaskId, IDL.Text, IDL.Text, Timestamp, IDL.Opt(UserId)],
      [IDL.Bool],
      [],
    ),
  'updateTaskStatus' : IDL.Func([TaskId, TaskStatus], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ProjectId = IDL.Nat;
  const UserId = IDL.Principal;
  const ProjectRole = IDL.Variant({ 'member' : IDL.Null, 'admin' : IDL.Null });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Timestamp = IDL.Int;
  const TaskId = IDL.Nat;
  const UserProfile = IDL.Record({ 'displayName' : IDL.Text });
  const DashboardStats = IDL.Record({
    'total' : IDL.Nat,
    'pending' : IDL.Nat,
    'completed' : IDL.Nat,
    'overdue' : IDL.Nat,
  });
  const ProjectMember = IDL.Record({ 'userId' : UserId, 'role' : ProjectRole });
  const ProjectView = IDL.Record({
    'id' : ProjectId,
    'members' : IDL.Vec(ProjectMember),
    'name' : IDL.Text,
    'createdBy' : UserId,
    'description' : IDL.Text,
  });
  const TaskStatus = IDL.Variant({
    'toDo' : IDL.Null,
    'completed' : IDL.Null,
    'inProgress' : IDL.Null,
  });
  const TaskView = IDL.Record({
    'id' : TaskId,
    'status' : TaskStatus,
    'title' : IDL.Text,
    'assignedTo' : IDL.Opt(UserId),
    'createdAt' : Timestamp,
    'createdBy' : UserId,
    'dueDate' : Timestamp,
    'description' : IDL.Text,
    'projectId' : ProjectId,
    'isOverdue' : IDL.Bool,
  });
  
  return IDL.Service({
    '_initializeAccessControl' : IDL.Func([], [], []),
    'addProjectMember' : IDL.Func(
        [ProjectId, UserId, ProjectRole],
        [IDL.Bool],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createProject' : IDL.Func([IDL.Text, IDL.Text], [ProjectId], []),
    'createTask' : IDL.Func(
        [ProjectId, IDL.Text, IDL.Text, Timestamp, IDL.Opt(UserId)],
        [TaskId],
        [],
      ),
    'deleteProject' : IDL.Func([ProjectId], [IDL.Bool], []),
    'deleteTask' : IDL.Func([TaskId], [IDL.Bool], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDashboard' : IDL.Func([], [DashboardStats], ['query']),
    'getProject' : IDL.Func([ProjectId], [IDL.Opt(ProjectView)], ['query']),
    'getTask' : IDL.Func([TaskId], [IDL.Opt(TaskView)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listMyProjects' : IDL.Func([], [IDL.Vec(ProjectView)], ['query']),
    'listProjectTasks' : IDL.Func([ProjectId], [IDL.Vec(TaskView)], ['query']),
    'removeProjectMember' : IDL.Func([ProjectId, UserId], [IDL.Bool], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateProject' : IDL.Func([ProjectId, IDL.Text, IDL.Text], [IDL.Bool], []),
    'updateProjectMemberRole' : IDL.Func(
        [ProjectId, UserId, ProjectRole],
        [IDL.Bool],
        [],
      ),
    'updateTask' : IDL.Func(
        [TaskId, IDL.Text, IDL.Text, Timestamp, IDL.Opt(UserId)],
        [IDL.Bool],
        [],
      ),
    'updateTaskStatus' : IDL.Func([TaskId, TaskStatus], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };