/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface DashboardStats {
  'total' : bigint,
  'pending' : bigint,
  'completed' : bigint,
  'overdue' : bigint,
}
export type ProjectId = bigint;
export interface ProjectMember { 'userId' : UserId, 'role' : ProjectRole }
export type ProjectRole = { 'member' : null } |
  { 'admin' : null };
export interface ProjectView {
  'id' : ProjectId,
  'members' : Array<ProjectMember>,
  'name' : string,
  'createdBy' : UserId,
  'description' : string,
}
export type TaskId = bigint;
export type TaskStatus = { 'toDo' : null } |
  { 'completed' : null } |
  { 'inProgress' : null };
export interface TaskView {
  'id' : TaskId,
  'status' : TaskStatus,
  'title' : string,
  'assignedTo' : [] | [UserId],
  'createdAt' : Timestamp,
  'createdBy' : UserId,
  'dueDate' : Timestamp,
  'description' : string,
  'projectId' : ProjectId,
  'isOverdue' : boolean,
}
export type Timestamp = bigint;
export type UserId = Principal;
export interface UserProfile { 'displayName' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'addProjectMember' : ActorMethod<[ProjectId, UserId, ProjectRole], boolean>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createProject' : ActorMethod<[string, string], ProjectId>,
  'createTask' : ActorMethod<
    [ProjectId, string, string, Timestamp, [] | [UserId]],
    TaskId
  >,
  'deleteProject' : ActorMethod<[ProjectId], boolean>,
  'deleteTask' : ActorMethod<[TaskId], boolean>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDashboard' : ActorMethod<[], DashboardStats>,
  'getProject' : ActorMethod<[ProjectId], [] | [ProjectView]>,
  'getTask' : ActorMethod<[TaskId], [] | [TaskView]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listMyProjects' : ActorMethod<[], Array<ProjectView>>,
  'listProjectTasks' : ActorMethod<[ProjectId], Array<TaskView>>,
  'removeProjectMember' : ActorMethod<[ProjectId, UserId], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateProject' : ActorMethod<[ProjectId, string, string], boolean>,
  'updateProjectMemberRole' : ActorMethod<
    [ProjectId, UserId, ProjectRole],
    boolean
  >,
  'updateTask' : ActorMethod<
    [TaskId, string, string, Timestamp, [] | [UserId]],
    boolean
  >,
  'updateTaskStatus' : ActorMethod<[TaskId, TaskStatus], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];