/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type UserId = Principal;
export type Timestamp = bigint;
export interface TaskView {
    id: TaskId;
    status: TaskStatus;
    title: string;
    assignedTo?: UserId;
    createdAt: Timestamp;
    createdBy: UserId;
    dueDate: Timestamp;
    description: string;
    projectId: ProjectId;
    isOverdue: boolean;
}
export interface ProjectMember {
    userId: UserId;
    role: ProjectRole;
}
export type TaskId = bigint;
export interface ProjectView {
    id: ProjectId;
    members: Array<ProjectMember>;
    name: string;
    createdBy: UserId;
    description: string;
}
export type ProjectId = bigint;
export interface DashboardStats {
    total: bigint;
    pending: bigint;
    completed: bigint;
    overdue: bigint;
}
export interface UserProfile {
    displayName: string;
}
export enum ProjectRole {
    member = "member",
    admin = "admin"
}
export enum TaskStatus {
    toDo = "toDo",
    completed = "completed",
    inProgress = "inProgress"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControl(): Promise<void>;
    addProjectMember(projectId: ProjectId, userId: UserId, role: ProjectRole): Promise<boolean>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createProject(name: string, description: string): Promise<ProjectId>;
    createTask(projectId: ProjectId, title: string, description: string, dueDate: Timestamp, assignedTo: UserId | null): Promise<TaskId>;
    deleteProject(id: ProjectId): Promise<boolean>;
    deleteTask(id: TaskId): Promise<boolean>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getDashboard(): Promise<DashboardStats>;
    getProject(id: ProjectId): Promise<ProjectView | null>;
    getTask(id: TaskId): Promise<TaskView | null>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    listMyProjects(): Promise<Array<ProjectView>>;
    listProjectTasks(projectId: ProjectId): Promise<Array<TaskView>>;
    removeProjectMember(projectId: ProjectId, userId: UserId): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    updateProject(id: ProjectId, name: string, description: string): Promise<boolean>;
    updateProjectMemberRole(projectId: ProjectId, userId: UserId, role: ProjectRole): Promise<boolean>;
    updateTask(id: TaskId, title: string, description: string, dueDate: Timestamp, assignedTo: UserId | null): Promise<boolean>;
    updateTaskStatus(id: TaskId, status: TaskStatus): Promise<boolean>;
}
import type { ProjectId as _ProjectId, ProjectMember as _ProjectMember, ProjectRole as _ProjectRole, ProjectView as _ProjectView, TaskId as _TaskId, TaskStatus as _TaskStatus, TaskView as _TaskView, Timestamp as _Timestamp, UserId as _UserId, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControl(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControl();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControl();
            return result;
        }
    }
    async addProjectMember(arg0: ProjectId, arg1: UserId, arg2: ProjectRole): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.addProjectMember(arg0, arg1, to_candid_ProjectRole_n1(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addProjectMember(arg0, arg1, to_candid_ProjectRole_n1(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n3(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n3(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createProject(arg0: string, arg1: string): Promise<ProjectId> {
        if (this.processError) {
            try {
                const result = await this.actor.createProject(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createProject(arg0, arg1);
            return result;
        }
    }
    async createTask(arg0: ProjectId, arg1: string, arg2: string, arg3: Timestamp, arg4: UserId | null): Promise<TaskId> {
        if (this.processError) {
            try {
                const result = await this.actor.createTask(arg0, arg1, arg2, arg3, to_candid_opt_n5(this._uploadFile, this._downloadFile, arg4));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createTask(arg0, arg1, arg2, arg3, to_candid_opt_n5(this._uploadFile, this._downloadFile, arg4));
            return result;
        }
    }
    async deleteProject(arg0: ProjectId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteProject(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteProject(arg0);
            return result;
        }
    }
    async deleteTask(arg0: TaskId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteTask(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteTask(arg0);
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDashboard(): Promise<DashboardStats> {
        if (this.processError) {
            try {
                const result = await this.actor.getDashboard();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDashboard();
            return result;
        }
    }
    async getProject(arg0: ProjectId): Promise<ProjectView | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getProject(arg0);
                return from_candid_opt_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProject(arg0);
            return from_candid_opt_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTask(arg0: TaskId): Promise<TaskView | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getTask(arg0);
                return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTask(arg0);
            return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async listMyProjects(): Promise<Array<ProjectView>> {
        if (this.processError) {
            try {
                const result = await this.actor.listMyProjects();
                return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listMyProjects();
            return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async listProjectTasks(arg0: ProjectId): Promise<Array<TaskView>> {
        if (this.processError) {
            try {
                const result = await this.actor.listProjectTasks(arg0);
                return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listProjectTasks(arg0);
            return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async removeProjectMember(arg0: ProjectId, arg1: UserId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.removeProjectMember(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeProjectMember(arg0, arg1);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async updateProject(arg0: ProjectId, arg1: string, arg2: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProject(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProject(arg0, arg1, arg2);
            return result;
        }
    }
    async updateProjectMemberRole(arg0: ProjectId, arg1: UserId, arg2: ProjectRole): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProjectMemberRole(arg0, arg1, to_candid_ProjectRole_n1(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProjectMemberRole(arg0, arg1, to_candid_ProjectRole_n1(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async updateTask(arg0: TaskId, arg1: string, arg2: string, arg3: Timestamp, arg4: UserId | null): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTask(arg0, arg1, arg2, arg3, to_candid_opt_n5(this._uploadFile, this._downloadFile, arg4));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTask(arg0, arg1, arg2, arg3, to_candid_opt_n5(this._uploadFile, this._downloadFile, arg4));
            return result;
        }
    }
    async updateTaskStatus(arg0: TaskId, arg1: TaskStatus): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTaskStatus(arg0, to_candid_TaskStatus_n25(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTaskStatus(arg0, to_candid_TaskStatus_n25(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
function from_candid_ProjectMember_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ProjectMember): ProjectMember {
    return from_candid_record_n14(_uploadFile, _downloadFile, value);
}
function from_candid_ProjectRole_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ProjectRole): ProjectRole {
    return from_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function from_candid_ProjectView_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ProjectView): ProjectView {
    return from_candid_record_n11(_uploadFile, _downloadFile, value);
}
function from_candid_TaskStatus_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TaskStatus): TaskStatus {
    return from_candid_variant_n21(_uploadFile, _downloadFile, value);
}
function from_candid_TaskView_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TaskView): TaskView {
    return from_candid_record_n19(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_TaskView]): TaskView | null {
    return value.length === 0 ? null : from_candid_TaskView_n18(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserId]): UserId | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ProjectView]): ProjectView | null {
    return value.length === 0 ? null : from_candid_ProjectView_n10(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _ProjectId;
    members: Array<_ProjectMember>;
    name: string;
    createdBy: _UserId;
    description: string;
}): {
    id: ProjectId;
    members: Array<ProjectMember>;
    name: string;
    createdBy: UserId;
    description: string;
} {
    return {
        id: value.id,
        members: from_candid_vec_n12(_uploadFile, _downloadFile, value.members),
        name: value.name,
        createdBy: value.createdBy,
        description: value.description
    };
}
function from_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    userId: _UserId;
    role: _ProjectRole;
}): {
    userId: UserId;
    role: ProjectRole;
} {
    return {
        userId: value.userId,
        role: from_candid_ProjectRole_n15(_uploadFile, _downloadFile, value.role)
    };
}
function from_candid_record_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _TaskId;
    status: _TaskStatus;
    title: string;
    assignedTo: [] | [_UserId];
    createdAt: _Timestamp;
    createdBy: _UserId;
    dueDate: _Timestamp;
    description: string;
    projectId: _ProjectId;
    isOverdue: boolean;
}): {
    id: TaskId;
    status: TaskStatus;
    title: string;
    assignedTo?: UserId;
    createdAt: Timestamp;
    createdBy: UserId;
    dueDate: Timestamp;
    description: string;
    projectId: ProjectId;
    isOverdue: boolean;
} {
    return {
        id: value.id,
        status: from_candid_TaskStatus_n20(_uploadFile, _downloadFile, value.status),
        title: value.title,
        assignedTo: record_opt_to_undefined(from_candid_opt_n22(_uploadFile, _downloadFile, value.assignedTo)),
        createdAt: value.createdAt,
        createdBy: value.createdBy,
        dueDate: value.dueDate,
        description: value.description,
        projectId: value.projectId,
        isOverdue: value.isOverdue
    };
}
function from_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    member: null;
} | {
    admin: null;
}): ProjectRole {
    return "member" in value ? ProjectRole.member : "admin" in value ? ProjectRole.admin : value;
}
function from_candid_variant_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    toDo: null;
} | {
    completed: null;
} | {
    inProgress: null;
}): TaskStatus {
    return "toDo" in value ? TaskStatus.toDo : "completed" in value ? TaskStatus.completed : "inProgress" in value ? TaskStatus.inProgress : value;
}
function from_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ProjectMember>): Array<ProjectMember> {
    return value.map((x)=>from_candid_ProjectMember_n13(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ProjectView>): Array<ProjectView> {
    return value.map((x)=>from_candid_ProjectView_n10(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_TaskView>): Array<TaskView> {
    return value.map((x)=>from_candid_TaskView_n18(_uploadFile, _downloadFile, x));
}
function to_candid_ProjectRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ProjectRole): _ProjectRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_TaskStatus_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TaskStatus): _TaskStatus {
    return to_candid_variant_n26(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserId | null): [] | [_UserId] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ProjectRole): {
    member: null;
} | {
    admin: null;
} {
    return value == ProjectRole.member ? {
        member: null
    } : value == ProjectRole.admin ? {
        admin: null
    } : value;
}
function to_candid_variant_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TaskStatus): {
    toDo: null;
} | {
    completed: null;
} | {
    inProgress: null;
} {
    return value == TaskStatus.toDo ? {
        toDo: null
    } : value == TaskStatus.completed ? {
        completed: null
    } : value == TaskStatus.inProgress ? {
        inProgress: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
